In [ ]:
!pip install matplotlib-venn

In [ ]:
!unzip /content/NN5Ppython-20240427T124003Z-001.zip
%ls

Archive:  /content/NN5Ppython-20240427T124003Z-001.zip
  inflating: NN5Ppython/README.txt   
  inflating: NN5Ppython/__init__.py  
  inflating: NN5Ppython/weights.h5   
  inflating: NN5Ppython/model.py     
drive/  NN5Ppython/  NN5Ppython-20240427T124003Z-001.zip  sample_data/


In [ ]:
import NN5Ppython

model = NN5Ppython.load_model()


In [ ]:
import os

files = os.listdir('/content/drive/MyDrive/BER/543_img_256')
print(files)

['105.png', '102.png', '103.png', '100.png', '1.png', '0.png', '101.png', '10.png', '104.png', '123.png', '119.png', '116.png', '12.png', '118.png', '120.png', '117.png', '121.png', '122.png', '115.png', '114.png', '111.png', '112.png', '108.png', '113.png', '107.png', '11.png', '110.png', '109.png', '106.png', '13.png', '127.png', '125.png', '124.png', '126.png', '129.png', '130.png', '128.png', '131.png', '133.png', '132.png', '140.png', '135.png', '138.png', '134.png', '136.png', '139.png', '14.png', '137.png', '141.png', '160.png', '16.png', '154.png', '156.png', '155.png', '157.png', '158.png', '152.png', '153.png', '159.png', '151.png', '150.png', '143.png', '145.png', '148.png', '147.png', '149.png', '144.png', '146.png', '15.png', '142.png', '186.png', '179.png', '178.png', '175.png', '173.png', '171.png', '172.png', '176.png', '170.png', '174.png', '177.png', '17.png', '169.png', '166.png', '164.png', '167.png', '161.png', '165.png', '163.png', '162.png', '168.png', '217.png',

In [ ]:
print(len(files))

256


In [ ]:
import numpy as np
import tensorflow as tf
from PIL import Image

In [ ]:
for i in range(256):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255


In [ ]:
list_name_dir = ['202','2691','1000','1052','1388','1396', '1408', '1547', '1561','2712', '2072', '543', '553', '2779',
              '325', '337', '427', '481', '487', '522']

In [ ]:
final_message1 = []
final1 = []
for j in list_name_dir:
  result = 0
  for i in range(256):
    I = np.asarray(Image.open(f'/content/drive/MyDrive/BER/real/256/{j}_img/{i}.png'))
    tensor = tf.convert_to_tensor(I)
    tensor_with_batch = tensor[tf.newaxis, ...]
    pred = model.predict(tensor_with_batch)
    print(pred[0][0],pred[0][1])
    if pred[0][0] > pred[0][1]:
      result = 0
    elif pred[0][0] <= pred[0][1]:
      result = 1
    final_message1.append(result)
  final1.append(final_message1)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 18ms/step
0.5456874 0.45431262
1/1 [==============================] - 0s 17ms/step
0.6167391 0.3832609
1/1 [==============================] - 0s 18ms/step
0.5936981 0.40630192
1/1 [==============================] - 0s 17ms/step
0.5698177 0.4301823
1/1 [==============================] - 0s 18ms/step
0.99799263 0.002007416
1/1 [==============================] - 0s 20ms/step
0.04893864 0.9510613
1/1 [==============================] - 0s 18ms/step
0.04893864 0.9510613
1/1 [==============================] - 0s 18ms/step
0.04893864 0.9510613
1/1 [==============================] - 0s 17ms/step
0.9466001 0.053399947
1/1 [==============================] - 0s 17ms/step
0.58490586 0.41509414
1/1 [==============================] - 0s 18ms/step
0.5951829 0.40481713
1/1 [==============================] - 0s 17ms/step
0.56792057 0.4320794
1/1 [==============================] - 0s 20ms/step
0.5580718 0.4419282

In [ ]:
final_message = []
final = []
for j in list_name_dir:
  result = 0
  for i in range(256):
    I = np.asarray(Image.open(f'/content/drive/MyDrive/BER/input/256/{j}_img/{i}.png'))
    tensor = tf.convert_to_tensor(I)
    tensor_with_batch = tensor[tf.newaxis, ...]
    pred = model.predict(tensor_with_batch)
    print(pred[0][0],pred[0][1])
    if pred[0][0] > pred[0][1]:
      result = 0
    elif pred[0][0] <= pred[0][1]:
      result = 1
    final_message.append(result)
  final.append(final_message)


In [ ]:
print(final_message1)

In [ ]:
import statistics as s
ber_list = []
for i in range(len(final)):
  ber = 0.0
  k = 0.0
  for j in range(256):
    if final[i][j] == final1[i][j]:
      k = k + 1
    ber = k / 256
  ber_list.append(ber)

print(s.mean(ber_list))

In [ ]:
ber = 0
for i in range(len(final_message)):
  if final_message[i] == final_message1[i]:
    ber = ber + 1

print(ber)

154


In [ ]:
import tensorflow as tf

In [ ]:

from PIL import Image
import numpy as np

In [ ]:
I = np.asarray(Image.open('/content/drive/MyDrive/BER/ber_input/1000.png'))

In [ ]:
print(I.shape)

(512, 512, 3)


In [ ]:

l1 = 0
l2 = 0
l3 = 0
l4 = 0
k = 0
for i in range(16):
  l1 = l2
  l2 = l2 + 32
  l4 = 0
  l3 = l4
  l3 = l4
  for j in range(16):
    l4 = l4 + 32
    print(l1,l2,' ', l3, l4)
    l3 = l4
    k = k + 1
  print()


0 32   0 32
0 32   32 64
0 32   64 96
0 32   96 128
0 32   128 160
0 32   160 192
0 32   192 224
0 32   224 256
0 32   256 288
0 32   288 320
0 32   320 352
0 32   352 384
0 32   384 416
0 32   416 448
0 32   448 480
0 32   480 512

32 64   0 32
32 64   32 64
32 64   64 96
32 64   96 128
32 64   128 160
32 64   160 192
32 64   192 224
32 64   224 256
32 64   256 288
32 64   288 320
32 64   320 352
32 64   352 384
32 64   384 416
32 64   416 448
32 64   448 480
32 64   480 512

64 96   0 32
64 96   32 64
64 96   64 96
64 96   96 128
64 96   128 160
64 96   160 192
64 96   192 224
64 96   224 256
64 96   256 288
64 96   288 320
64 96   320 352
64 96   352 384
64 96   384 416
64 96   416 448
64 96   448 480
64 96   480 512

96 128   0 32
96 128   32 64
96 128   64 96
96 128   96 128
96 128   128 160
96 128   160 192
96 128   192 224
96 128   224 256
96 128   256 288
96 128   288 320
96 128   320 352
96 128   352 384
96 128   384 416
96 128   416 448
96 128   448 480
96 128   480 512

128 

512


In [ ]:
i_shape = I[0:32,32:64,0:3]

In [ ]:
i_shape.shape

(32, 32, 3)

In [ ]:
tensor = tf.convert_to_tensor(i_shape)

In [ ]:
tensor.shape

TensorShape([32, 32, 3])

In [ ]:
tensor_with_batch = tensor[tf.newaxis, ...]

In [ ]:
tensor_with_batch.shape

TensorShape([1, 32, 32, 3])

In [ ]:
i_shape.shape

(32, 32, 3)

In [ ]:
a = model.predict(tensor_with_batch)

1/1 [==============================] - 0s 30ms/step


In [ ]:
print(a[0][1])

0.94181395


In [ ]:
if a[0][0] > a[0][1]:
  result = 0
else:
  result = 1

print(result)

1


In [ ]:
l1 = 0
l2 = 0
l3 = 0
l4 = 0
k = 0
string1 = ''
result = 0
final_message1 = []
final_messages = []
for i in range(16):
  l1 = l2
  l2 = l2 + 32
  l4 = 0
  l3 = l4
  l3 = l4
  for j in range(16):
    print('--------------------------')
    k = k + 1
    print(f'Обрезок {k}')
    l4 = l4 + 32
    print('Его координаты: ', l1, l2, ' ', l3, l4)
    i_shape = I[l1:l2,l3:l4,0:3]
    print('Его размеры: ', i_shape.shape)
    tensor = tf.convert_to_tensor(i_shape)
    print('Размеры тензора: ', tensor.shape)
    tensor_with_batch = tensor[tf.newaxis, ...]
    a = model.predict(tensor_with_batch)
    if a[0][0] > a[0][1]:
      result = 0
    else:
      result = 1
    final_message1.append(result)
    l3 = l4

string1 = ''.join(map(str, final_message1))
final_messages.append(string1)

--------------------------
Обрезок 1
Его координаты:  0 32   0 32
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 23ms/step
--------------------------
Обрезок 2
Его координаты:  0 32   32 64
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 20ms/step
--------------------------
Обрезок 3
Его координаты:  0 32   64 96
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 4
Его координаты:  0 32   96 128
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 5
Его координаты:  0 32   128 160
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 6
Его координаты:  0 32   160 192
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3

In [ ]:
list_name = ['202.png','2691.png','1000.png','1052.png','1388.png','1396.png', '1408.png', '1547.png', '1561.png','2712.png', '2072.png', '543.png', '553.png', '2779.png',
              '325.png', '337.png', '427.png', '481.png', '487.png', '522.png']

In [ ]:
final_message1 = []
final_messages1 = []
for o in list_name:
  string = ''
  l1 = 0
  l2 = 0
  l3 = 0
  l4 = 0
  k = 0
  I = np.asarray(Image.open(f'/content/drive/MyDrive/BER/ber_input/{o}'))
  for i in range(16):
    print(o)
    l1 = l2
    l2 = l2 + 32
    l4 = 0
    l3 = l4
    l3 = l4
    for j in range(16):
      print('--------------------------')
      k = k + 1
      print(f'Обрезок {k}')
      l4 = l4 + 32
      print('Его координаты: ', l1, l2, ' ', l3, l4)
      i_shape = I[l3:l4,l1:l2,0:3]
      print('Его размеры: ', i_shape.shape)
      tensor = tf.convert_to_tensor(i_shape)
      print('Размеры тензора: ', tensor.shape)
      tensor_with_batch = tensor[tf.newaxis, ...]
      a = model.predict(tensor_with_batch)
      if a[0][0] > a[0][1]:
        result = 0
      else:
        result = 1
      final_message1.append(result)
      l3 = l4

  string1 = ''.join(map(str, final_message1))
  final_messages1.append(string1)


Выходные данные были обрезаны до нескольких последних строк (5000).
Его координаты:  384 416   224 256
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 201
Его координаты:  384 416   256 288
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 22ms/step
--------------------------
Обрезок 202
Его координаты:  384 416   288 320
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 203
Его координаты:  384 416   320 352
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 22ms/step
--------------------------
Обрезок 204
Его координаты:  384 416   352 384
Его размеры:  (32, 32, 3)
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 21ms/step
--------------------------
Обрезок 205
Его координаты:  384 4

In [ ]:
final_messages1

['1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111',
 '11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111',
 '1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

In [ ]:
string = ''.join(map(str, final_message))

In [ ]:
string

'1110110001101001001001000011000010101100010110011110001001110110001010100010101001101111110000110111010111011101011010001001110110000101110111011010011100001100011010010101100010101011001010010111001001010000101100111111001110000001011100110011010011001011'

In [ ]:
string1

'1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'

In [ ]:
count = 0
for i in range(len(string)):
  if string[i] == string1[i]:
    count = count + 1


In [ ]:
print(count)

128


In [ ]:
final_message

[1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,


In [ ]:
final_message2 = []
l1 = 0
l2 = 0
l3 = 0
l4 = 0
k = 0
B = np.asarray(Image.open(f'/content/drive/MyDrive/BER/ber_input/1000.png'))
for i in range(16):
  print(o)
  l1 = l2
  l2 = l2 + 32
  l4 = 0
  l3 = l4
  l3 = l4
  for j in range(16):
    print('--------------------------')
    k = k + 1
    print(f'Обрезок {k}')
    l4 = l4 + 32
    print('Его координаты: ', l1, l2, ' ', l3, l4)
    b_shape = B[l1:l2,l3:l4,0:3]
    print('Его размеры: ', b_shape.shape)
    tensorb = tf.convert_to_tensor(B[l1:l2,l3:l4,0:3])
    print(b_shape)
    print('Размеры тензора: ', tensorb.shape)
    tensor_with_batchb = tensor[tf.newaxis, ...]
    a = model.predict(tensor_with_batchb)
    print(a[0][0], a[0][1])
    if a[0][0] > a[0][1]:
      result = 0
    else:
      result = 1
    print(result)
    final_message2.append(result)
    l3 = l4



Выходные данные были обрезаны до нескольких последних строк (5000).
  [4 4 4]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  ...
  [4 4 4]
  [4 4 4]
  [4 4 4]]

 ...

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [4 4 4]
  [4 4 4]
  [4 4 4]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [4 4 4]
  [4 4 4]
  [4 4 4]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]
  ...
  [4 4 4]
  [4 4 4]
  [4 4 4]]]
Размеры тензора:  (32, 32, 3)
1/1 [==============================] - 0s 19ms/step
0.057274356 0.9427257
1
--------------------------
Обрезок 121
Его координаты:  224 256   256 288
Его размеры:  (32, 32, 3)
[[[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]

 ...

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [4 3 1]
  [5 4 2]
  [5 4 2]]]
Размеры тензора:  (32,

KeyboardInterrupt: 

In [ ]:
final_message2

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [ ]:
final_message

[0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,


In [ ]:
import tensorflow as tf
from PIL import Image

B = np.asarray(Image.open(f'/content/drive/MyDrive/BER/ber_input/2712.png'))
# img = Image.open('/content/drive/MyDrive/BER/ber_final/1000.png')

img_to_tensor = tf.convert_to_tensor(img)

print("dtype of tensor:",img_to_tensor.shape)

dtype of tensor: (512, 512, 3)


In [ ]:
reshaped_tensor = B.reshape(16, 32, 16, 32, 3).transpose(0, 2, 1, 3, 4).reshape(256, 32, 32, 3)

In [ ]:
print("Новая форма тензора:", reshaped_tensor.shape)

Новая форма тензора: (256, 32, 32, 3)


In [ ]:
a = model.predict(reshaped_tensor)

8/8 [==============================] - 0s 2ms/step


[0.8079421  0.19205791]
